"""LinkedIn copy-paste exporter.

Generates a structured plain-text file where each LinkedIn field is clearly
labeled so the user can copy sections directly into LinkedIn's interface.
"""

from __future__ import annotations


_DIVIDER = "=" * 60
_SUB_DIVIDER = "-" * 60


def export_linkedin(linkedin_data: dict, output_path: str) -> str:
    """Build a LinkedIn copy-paste .txt file. Returns output_path."""
    lines = []

    def section(title: str, instructions: str = ""):
        lines.append("")
        lines.append(_DIVIDER)
        lines.append(f"  {title.upper()}")
        if instructions:
            lines.append(f"  >> {instructions}")
        lines.append(_DIVIDER)

    lines.append("REVIZOR FRANK — LINKEDIN PROFILE COPY-PASTE FILE")
    lines.append("Generated by ReviZoR FranK CV Optimization Engine")
    lines.append(_DIVIDER)
    lines.append("INSTRUCTIONS:")
    lines.append("  For each section below, click inside the box, select all")
    lines.append("  text (Ctrl+A), copy (Ctrl+C), then paste into the")
    lines.append("  corresponding LinkedIn field.")
    lines.append(_DIVIDER)

    # ── Headline ──────────────────────────────────────────────────────────────
    section(
        "1. HEADLINE",
        "LinkedIn > Edit intro > Headline field (max 220 characters)"
    )
    lines.append("")
    lines.append(linkedin_data.get("headline", ""))
    lines.append("")
    headline = linkedin_data.get("headline", "")
    lines.append(f"  [Character count: {len(headline)}/220]")

    # ── About ─────────────────────────────────────────────────────────────────
    section(
        "2. ABOUT / SUMMARY",
        "LinkedIn > Edit intro > About section (max 2,600 characters)"
    )
    lines.append("")
    about = linkedin_data.get("about", "")
    lines.append(about)
    lines.append("")
    lines.append(f"  [Character count: {len(about)}/2600]")

    # ── Tagline ───────────────────────────────────────────────────────────────
    section(
        "3. SUMMARY TAGLINE",
        "Use in connection request notes, InMail, or as your cover note"
    )
    lines.append("")
    lines.append(linkedin_data.get("summary_tagline", ""))

    # ── Experience ────────────────────────────────────────────────────────────
    section(
        "4. EXPERIENCE",
        "LinkedIn > Add section > Work experience — one block per position"
    )
    for i, exp in enumerate(linkedin_data.get("experience", []), 1):
        lines.append("")
        lines.append(f"  --- Position {i} ---")
        lines.append(f"  Title:       {exp.get('title', '')}")
        lines.append(f"  Company:     {exp.get('company', '')}")
        lines.append(f"  Dates:       {exp.get('dates', '')}")
        lines.append("")
        lines.append("  Description (paste into LinkedIn's description field):")
        lines.append(_SUB_DIVIDER)
        lines.append(exp.get("description", ""))
        lines.append(_SUB_DIVIDER)
        desc = exp.get("description", "")
        lines.append(f"  [Character count: {len(desc)}/2000]")

    # ── Skills ────────────────────────────────────────────────────────────────
    section(
        "5. SKILLS",
        "LinkedIn > Add section > Skills — add each skill individually (max 50)"
    )
    lines.append("")
    skills = linkedin_data.get("skills", [])
    for i, skill in enumerate(skills[:50], 1):
        lines.append(f"  {i:2}. {skill}")

    # ── Education ─────────────────────────────────────────────────────────────
    section(
        "6. EDUCATION",
        "LinkedIn > Add section > Education — one block per institution"
    )
    for i, edu in enumerate(linkedin_data.get("education", []), 1):
        lines.append("")
        lines.append(f"  --- Education {i} ---")
        lines.append(f"  Degree:  {edu.get('degree', '')}")
        lines.append(f"  School:  {edu.get('school', '')}")
        lines.append(f"  Dates:   {edu.get('dates', '')}")

    # ── Certifications ────────────────────────────────────────────────────────
    if linkedin_data.get("certifications"):
        section(
            "7. LICENSES & CERTIFICATIONS",
            "LinkedIn > Add section > Licenses & certifications"
        )
        for i, cert in enumerate(linkedin_data["certifications"], 1):
            lines.append("")
            lines.append(f"  --- Certification {i} ---")
            lines.append(f"  Name:    {cert.get('name', '')}")
            lines.append(f"  Issuer:  {cert.get('issuer', '')}")
            lines.append(f"  Date:    {cert.get('date', '')}")

    lines.append("")
    lines.append(_DIVIDER)
    lines.append("  End of LinkedIn Profile — Generated by ReviZoR FranK")
    lines.append(_DIVIDER)

    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    return output_path
